CREATE TABLE person (
    person_id integer PRIMARY KEY,
    full_name VARCHAR(100),
    address VARCHAR(255)
);

INSERT INTO person (full_name, address) VALUES

('Elizabeth Diddlesworth', 'Diddlesworth Manor'),
('Billynette Diddlesworth', 'Diddlesworth Manor'),
('Doug Diddlesworth', 'Diddlesworth Manor'),
('Randy Diddlesworth', 'Diddlesworth Manor'),
('Michelle Diddlesworth', 'Diddlesworth Manor'),
('John Doe', 'Shadow Valley'),
('Jane Smith', 'Heavy Mountain View Valley'),
('Alice Johnson', 'Stardew Valley'),
('Bob Brown', 'Shadow Valley'),
('Charlie White', 'Heavy Mountain View Valley'),
('Daisy Green', 'Stardew Valley'),
('Ethan Blue', 'Shadow Valley'),
('Fiona Black', 'Heavy Mountain View Valley'),
('George Red', 'Stardew Valley'),
('Hannah Yellow', 'Shadow Valley'),
('Ian Purple', 'Heavy Mountain View Valley'),
('Jasmine Orange', 'Stardew Valley'),
('Kevin Pink', 'Shadow Valley'),
('Lily Gray', 'Heavy Mountain View Valley'),
('Mason Cyan', 'Stardew Valley'),
('Nora Magenta', 'Shadow Valley'),
('Oliver Brown', 'Heavy Mountain View Valley'),
('Penny Teal', 'Stardew Valley'),
('Quinn Indigo', 'Shadow Valley'),
('Ryan Violet', 'Heavy Mountain View Valley'),
('Sophie Gold', 'Stardew Valley'),
('Tyler Silver', 'Shadow Valley'),
('Uma Bronze', 'Heavy Mountain View Valley'),
('Victor Copper', 'Stardew Valley'),
('Wendy Platinum', 'Shadow Valley'),
('Xander Diamond', 'Heavy Mountain View Valley'),
('Yara Ruby', 'Stardew Valley'),
('Zane Emerald', 'Shadow Valley'),
('Ava Sapphire', 'Heavy Mountain View Valley'),
('Liam Topaz', 'Stardew Valley'),
('Mia Amethyst', 'Shadow Valley'),
('Noah Garnet', 'Heavy Mountain View Valley'),
('Olivia Opal', 'Stardew Valley'),
('Lucas Peridot', 'Shadow Valley'),
('Emma Aquamarine', 'Heavy Mountain View Valley'),
('James Citrine', 'Stardew Valley'),
('Isabella Tourmaline', 'Shadow Valley'),
('Benjamin Tanzanite', 'Heavy Mountain View Valley'),
('Charlotte Zircon', 'Stardew Valley'),
('Alexander Onyx', 'Shadow Valley'),
('Sophia Jade', 'Heavy Mountain View Valley'),
('William Quartz', 'Stardew Valley'),
('Amelia Beryl', 'Shadow Valley'),
('Ethan Coral', 'Heavy Mountain View Valley'),
('Avery Diamond', 'Stardew Valley'),
('Jackson Pearl', 'Shadow Valley'),
('Scarlett Ruby', 'Heavy Mountain View Valley'),
('Geiko(IT GUY!)', 'Heavy Mountain View Valley'),
('Sebastian Sapphire', 'Stardew Valley'),
('Flynn Rider', 'Shadow Valley'),
('Grace Emerald', 'Shadow Valley'),
('Henry Garnet', 'Heavy Mountain View Valley'),
('Chloe Amethyst', 'Stardew Valley'),
('Daniel Opal', 'Shadow Valley'),
('Victoria Topaz', 'Heavy Mountain View Valley'),
('Matthew Aquamarine', 'Stardew Valley'),
('Samantha Citrine', 'Shadow Valley'),
('David Tourmaline', 'Heavy Mountain View Valley'),
('Madison Zircon', 'Stardew Valley'),
('Joseph Onyx', 'Shadow Valley'),
('Aubrey Jade', 'Heavy Mountain View Valley'),
('Samuel Quartz', 'Stardew Valley'),
('Ella Beryl', 'Shadow Valley'),
('Gabriel Coral', 'Heavy Mountain View Valley'),
('Luna Diamond', 'Stardew Valley'),
('Anthony Pearl', 'Shadow Valley'),
('Aria Ruby', 'Heavy Mountain View Valley'),
('Isaac Sapphire', 'Stardew Valley'),
('Natalie Emerald', 'Shadow Valley'),
('Christopher Garnet', 'Heavy Mountain View Valley'),
('Zoe Amethyst', 'Stardew Valley'),
('Andrew Opal', 'Shadow Valley'),
('Mila Topaz', 'Heavy Mountain View Valley'),
('Joshua Aquamarine', 'Stardew Valley'),
('Sofia Citrine', 'Shadow Valley'),
('Elijah Tourmaline', 'Heavy Mountain View Valley'),
('Aaliyah Zircon', 'Stardew Valley'),
('Caleb Onyx', 'Shadow Valley'),
('Layla Jade', 'Heavy Mountain View Valley'),
('Nathan Quartz', 'Stardew Valley'),
('Hannah Beryl', 'Shadow Valley'),
('Isaiah Coral', 'Heavy Mountain View Valley'),
('Lydia Diamond', 'Stardew Valley');
